apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
    - name: tg-redirect
      image: prajapatdip/tg-redirect:1.0
      ports:
      - containerPort: 8081
